"""
CardDesk test inventory seed script.

How to use:
1. Put this file in your CardDesk project root beside app.py.
2. Run:
   python seed_test_cards.py

It will add a mixed test inventory set without overwriting existing cards.
Existing TEST-* card codes are skipped.
"""

from models import db, Card
from app import app


TEST_CARDS = [
    {
        "card_code": "TEST-001",
        "player_name": "Ken Griffey Jr",
        "year": 1989,
        "sport": "Baseball",
        "brand": "Upper Deck",
        "set_name": "Upper Deck",
        "card_number": "1",
        "variation": "",
        "card_type": "Raw",
        "grade_estimate": "NM-MT",
        "purchase_price": 35.00,
        "estimated_value": 55.00,
        "asking_price": 65.00,
        "acquisition_date": "2025-10-01",
        "storage_location": "Box A / Row 1",
    },
    {
        "card_code": "TEST-002",
        "player_name": "Ken Griffey Jr",
        "year": 1989,
        "sport": "Baseball",
        "brand": "Upper Deck",
        "set_name": "Upper Deck",
        "card_number": "1",
        "variation": "",
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "9",
        "purchase_price": 80.00,
        "estimated_value": 120.00,
        "asking_price": 140.00,
        "acquisition_date": "2025-09-15",
        "storage_location": "Slab Case 1",
    },
    {
        "card_code": "TEST-003",
        "player_name": "Ken Griffey Jr",
        "year": 1989,
        "sport": "Baseball",
        "brand": "Upper Deck",
        "set_name": "Upper Deck",
        "card_number": "1",
        "variation": "",
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "10",
        "purchase_price": 950.00,
        "estimated_value": 1500.00,
        "asking_price": 1700.00,
        "acquisition_date": "2025-07-01",
        "storage_location": "Show Case / Premium",
    },
    {
        "card_code": "TEST-004",
        "player_name": "Michael Jordan",
        "year": 1990,
        "sport": "Basketball",
        "brand": "Fleer",
        "set_name": "Fleer",
        "card_number": "26",
        "card_type": "Raw",
        "grade_estimate": "NM",
        "purchase_price": 8.00,
        "estimated_value": 15.00,
        "asking_price": 20.00,
        "acquisition_date": "2026-05-20",
        "storage_location": "Box B / Basketball",
    },
    {
        "card_code": "TEST-005",
        "player_name": "Michael Jordan",
        "year": 1988,
        "sport": "Basketball",
        "brand": "Fleer",
        "set_name": "Fleer",
        "card_number": "17",
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "9",
        "purchase_price": 150.00,
        "estimated_value": 250.00,
        "asking_price": 300.00,
        "acquisition_date": "2025-11-01",
        "storage_location": "Slab Case 2",
    },
    {
        "card_code": "TEST-006",
        "player_name": "Joe Burrow",
        "year": 2020,
        "sport": "Football",
        "brand": "Panini Prizm",
        "set_name": "Prizm",
        "card_number": "307",
        "variation": "Rookie",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "NM-MT",
        "purchase_price": 25.00,
        "estimated_value": 40.00,
        "asking_price": 50.00,
        "acquisition_date": "2026-01-01",
        "storage_location": "Box C / Football",
    },
    {
        "card_code": "TEST-007",
        "player_name": "Joe Burrow",
        "year": 2020,
        "sport": "Football",
        "brand": "Panini Prizm",
        "set_name": "Prizm",
        "card_number": "307",
        "variation": "Rookie",
        "is_rookie": True,
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "10",
        "purchase_price": 250.00,
        "estimated_value": 450.00,
        "asking_price": 500.00,
        "acquisition_date": "2025-08-01",
        "storage_location": "Slab Case 1",
    },
    {
        "card_code": "TEST-008",
        "player_name": "Elly De La Cruz",
        "year": 2024,
        "sport": "Baseball",
        "brand": "Topps Chrome",
        "set_name": "Topps Chrome",
        "card_number": "150",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "NM-MT",
        "purchase_price": 12.00,
        "estimated_value": 20.00,
        "asking_price": 25.00,
        "acquisition_date": "2026-04-10",
        "storage_location": "Box A / Row 2",
    },
    {
        "card_code": "TEST-009",
        "player_name": "Elly De La Cruz",
        "year": 2024,
        "sport": "Baseball",
        "brand": "Topps Chrome",
        "set_name": "Topps Chrome",
        "card_number": "150",
        "is_rookie": True,
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "10",
        "purchase_price": 90.00,
        "estimated_value": 160.00,
        "asking_price": 180.00,
        "acquisition_date": "2026-03-20",
        "storage_location": "Slab Case 3",
    },
    {
        "card_code": "TEST-010",
        "player_name": "Shohei Ohtani",
        "year": 2018,
        "sport": "Baseball",
        "brand": "Topps Update",
        "set_name": "Topps Update",
        "card_number": "US1",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "NM-MT",
        "purchase_price": 30.00,
        "estimated_value": 50.00,
        "asking_price": 60.00,
        "acquisition_date": "2025-12-15",
        "storage_location": "Box A / Row 3",
    },
    {
        "card_code": "TEST-011",
        "player_name": "Ronald Acuna Jr",
        "year": 2018,
        "sport": "Baseball",
        "brand": "Topps Update",
        "set_name": "Topps Update",
        "card_number": "US250",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "NM-MT",
        "purchase_price": 35.00,
        "estimated_value": 65.00,
        "asking_price": 75.00,
        "acquisition_date": "2025-06-15",
        "storage_location": "Box A / Row 3",
    },
    {
        "card_code": "TEST-012",
        "player_name": "Ronald Acuna Jr",
        "year": 2018,
        "sport": "Baseball",
        "brand": "Topps Update",
        "set_name": "Topps Update",
        "card_number": "US250",
        "is_rookie": True,
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "10",
        "purchase_price": 325.00,
        "estimated_value": 550.00,
        "asking_price": 625.00,
        "acquisition_date": "2025-05-01",
        "storage_location": "Show Case / Premium",
    },
    {
        "card_code": "TEST-013",
        "player_name": "Aaron Judge",
        "year": 2017,
        "sport": "Baseball",
        "brand": "Topps",
        "set_name": "Topps",
        "card_number": "287",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "NM",
        "purchase_price": 10.00,
        "estimated_value": 18.00,
        "asking_price": 22.00,
        "acquisition_date": "2026-04-01",
        "storage_location": "Box A / Row 4",
    },
    {
        "card_code": "TEST-014",
        "player_name": "Patrick Mahomes",
        "year": 2017,
        "sport": "Football",
        "brand": "Donruss",
        "set_name": "Donruss",
        "card_number": "327",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "NM",
        "purchase_price": 30.00,
        "estimated_value": 45.00,
        "asking_price": 55.00,
        "acquisition_date": "2025-09-01",
        "storage_location": "Box C / Football",
    },
    {
        "card_code": "TEST-015",
        "player_name": "Patrick Mahomes",
        "year": 2017,
        "sport": "Football",
        "brand": "Donruss",
        "set_name": "Donruss",
        "card_number": "327",
        "is_rookie": True,
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "9",
        "purchase_price": 175.00,
        "estimated_value": 275.00,
        "asking_price": 325.00,
        "acquisition_date": "2025-04-01",
        "storage_location": "Slab Case 2",
    },
    {
        "card_code": "TEST-016",
        "player_name": "Tom Brady",
        "year": 2000,
        "sport": "Football",
        "brand": "Bowman",
        "set_name": "Bowman",
        "card_number": "236",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "VG-EX",
        "purchase_price": 150.00,
        "estimated_value": 225.00,
        "asking_price": 250.00,
        "acquisition_date": "2025-01-15",
        "storage_location": "Box C / Football",
    },
    {
        "card_code": "TEST-017",
        "player_name": "Tom Brady",
        "year": 2000,
        "sport": "Football",
        "brand": "Bowman",
        "set_name": "Bowman",
        "card_number": "236",
        "is_rookie": True,
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "8",
        "purchase_price": 850.00,
        "estimated_value": 1250.00,
        "asking_price": 1450.00,
        "acquisition_date": "2024-12-01",
        "storage_location": "Show Case / Premium",
    },
    {
        "card_code": "TEST-018",
        "player_name": "Mickey Mantle",
        "year": 1964,
        "sport": "Baseball",
        "brand": "Topps",
        "set_name": "Topps",
        "card_number": "50",
        "is_hof": True,
        "card_type": "Raw",
        "grade_estimate": "VG",
        "purchase_price": 125.00,
        "estimated_value": 175.00,
        "asking_price": 225.00,
        "acquisition_date": "2024-10-01",
        "storage_location": "Vintage Box",
    },
    {
        "card_code": "TEST-019",
        "player_name": "Willie Mays",
        "year": 1965,
        "sport": "Baseball",
        "brand": "Topps",
        "set_name": "Topps",
        "card_number": "250",
        "is_hof": True,
        "card_type": "Raw",
        "grade_estimate": "EX",
        "purchase_price": 75.00,
        "estimated_value": 110.00,
        "asking_price": 140.00,
        "acquisition_date": "2025-02-01",
        "storage_location": "Vintage Box",
    },
    {
        "card_code": "TEST-020",
        "player_name": "Babe Ruth",
        "year": 2023,
        "sport": "Baseball",
        "brand": "Topps Archives",
        "set_name": "Topps Archives",
        "card_number": "15",
        "is_hof": True,
        "card_type": "Raw",
        "grade_estimate": "NM-MT",
        "purchase_price": 8.00,
        "estimated_value": 15.00,
        "asking_price": 20.00,
        "acquisition_date": "2026-05-01",
        "storage_location": "",
    },
    {
        "card_code": "TEST-021",
        "player_name": "Caitlin Clark",
        "year": 2024,
        "sport": "Basketball",
        "brand": "Panini Instant",
        "set_name": "Panini Instant",
        "card_number": "1",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "NM-MT",
        "purchase_price": 20.00,
        "estimated_value": 35.00,
        "asking_price": 40.00,
        "acquisition_date": "2026-04-20",
        "storage_location": "Box B / Basketball",
    },
    {
        "card_code": "TEST-022",
        "player_name": "Victor Wembanyama",
        "year": 2024,
        "sport": "Basketball",
        "brand": "Prizm",
        "set_name": "Prizm",
        "card_number": "136",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "NM-MT",
        "purchase_price": 18.00,
        "estimated_value": 30.00,
        "asking_price": 35.00,
        "acquisition_date": "2026-03-15",
        "storage_location": "Box B / Basketball",
    },
    {
        "card_code": "TEST-023",
        "player_name": "Victor Wembanyama",
        "year": 2024,
        "sport": "Basketball",
        "brand": "Prizm",
        "set_name": "Prizm",
        "card_number": "136",
        "is_rookie": True,
        "card_type": "Graded",
        "grading_company": "PSA",
        "actual_grade": "10",
        "purchase_price": 120.00,
        "estimated_value": 225.00,
        "asking_price": 250.00,
        "acquisition_date": "2026-02-15",
        "storage_location": "Slab Case 3",
    },
    {
        "card_code": "TEST-024",
        "player_name": "Kobe Bryant",
        "year": 1996,
        "sport": "Basketball",
        "brand": "Topps",
        "set_name": "Topps",
        "card_number": "138",
        "is_rookie": True,
        "card_type": "Raw",
        "grade_estimate": "EX-NM",
        "purchase_price": 75.00,
        "estimated_value": 120.00,
        "asking_price": 150.00,
        "acquisition_date": "2025-03-01",
        "storage_location": "Box B / Basketball",
    },
    {
        "card_code": "TEST-025",
        "player_name": "Kobe Bryant",
        "year": 1996,
        "sport": "Basketball",
        "brand": "Topps",
        "set_name": "Topps",
        "card_number": "138",
        "is_rookie": True,
        "card_type": "Graded",
        "grading_company": "BGS",
        "actual_grade": "9.5",
        "purchase_price": 450.00,
        "estimated_value": 750.00,
        "asking_price": 850.00,
        "acquisition_date": "2024-11-01",
        "storage_location": "Show Case / Premium",
    },
]


def seed_test_cards():
    added = 0
    skipped = 0

    for data in TEST_CARDS:
        existing = Card.query.filter_by(card_code=data["card_code"]).first()

        if existing:
            skipped += 1
            continue

        card = Card(
            quantity=1,
            status="Active",
            collection_type="Inventory",
            acquisition_source="Test Seed",
            acquisition_event="CardDesk Test Load",
            fulfillment_status="In Storage",
            **data,
        )

        db.session.add(card)
        added += 1

    db.session.commit()

    print(f"Seed complete. Added: {added}. Skipped existing: {skipped}.")


if __name__ == "__main__":
    with app.app_context():
        seed_test_cards()
